import { IURL } from './interface';
export const URLs: IURL[] = [
    { longURL: 'https://www.thisisthelongesturlthatcaneverhappen.com/', shortURL: "thisisthelongesturlthatcaneverhappen"},
    { longURL: 'https://www.youtube.com/', shortURL: "youtube" },
    { longURL: 'https://www.google.com/', shortURL: "google"},
    { longURL: 'https://www.amazon.com/', shortURL: "amazon"},
    { longURL: 'https://www.facebook.com/', shortURL: "facebook"},
    { longURL: 'https://www.twitter.com/', shortURL: "twitter"},
    { longURL: 'https://www.instagram.com/', shortURL: "instagram"},
    { longURL: 'https://www.reddit.com/', shortURL: "reddit"},
    { longURL: 'https://www.netflix.com/', shortURL: "netflix"},
    { longURL: 'https://www.hulu.com/', shortURL: "hulu"},
    { longURL: 'https://www.disneyplus.com/', shortURL: "disneyplus"},
    { longURL: 'https://www.apple.com/', shortURL: "apple"},
    { longURL: 'https://www.microsoft.com/', shortURL: "microsoft"},
    { longURL: 'https://www.samsung.com/', shortURL: "samsung"},
    { longURL: 'https://www.lg.com/', shortURL: "lg"},
    { longURL: 'https://www.sony.com/', shortURL: "sony"},
    { longURL: 'https://www.nintendo.com/', shortURL: "nintendo"},
    { longURL: 'https://www.playstation.com/', shortURL: "playstation"},
    { longURL: 'https://www.xbox.com/', shortURL: "xbox"},
    { longURL: 'https://www.spotify.com/', shortURL: "spotify"},
    { longURL: 'https://www.apple.com/music/', shortURL: "applemusic"},
    { longURL: 'https://www.pandora.com/', shortURL: "pandora"},
    { longURL: 'https://www.soundcloud.com/', shortURL: "soundcloud"},
    { longURL: 'https://www.bandcamp.com/', shortURL: "bandcamp"},
    { longURL: 'https://www.tidal.com/', shortURL: "tidal"},
    { longURL: 'https://www.deezer.com/', shortURL: "deezer"},
    { longURL: 'https://www.amazon.com/music/', shortURL: "amazonmusic"},
    { longURL: 'https://www.google.com/music/', shortURL: "googlemusic"},
    { longURL: 'https://www.youtube.com/music/', shortURL: "youtubemusic"},
];